# Generated by Django 3.0.5 on 2020-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch'), ('hi', 'Hindi')], default='en-us', max_length=5)),
            ],
        ),
    ]
